name: Push to GitHub

on: [push, pull_request]

permissions:
  contents: read

jobs:
  pub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: wntrblm/nox@2022.8.7
        with:
          python-versions: "3.8, 3.9, 3.10, 3.11"
      - name: Run linting
        run: |
          make lint
